# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master

pool:
  vmImage: 'windows-latest'

# Start with a minimal pipeline that you can customize to build and deploy your code.
steps:
- task: AzureCLI@2
  displayName: Azure CLI storage
  inputs:
    azureSubscription: 'devops1'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
#    inlineScript: 'az storage blob upload-batch —-account-name stonebrancheurgdiag364 --account-key tL/I3bSPSyNfWz312rU+w6AQy868SLIhWh8iZxpRpCA+nJW0rDlugfp2veyJMiAsgQWVLNu6DIEmSPzyqcVfMA== —-destination oli —-source ./'
    inlineScript: 'az storage blob upload-batch --dryrun  --connection-string $(AZURE_STORAGE_CONNECTION_STRING) —-destination oli —-source ./'
    failOnStandardError: true

- task: AzureCLI@2
  displayName: Azure CLI version
  inputs:
    azureSubscription: 'devops1'
    scriptType: pscore
    scriptLocation: 'inlineScript'
    inlineScript: 'az --version'
    
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

